-- AlterTable
ALTER TABLE "Task" ADD COLUMN     "userId" INTEGER,
ALTER COLUMN "taskListId" DROP NOT NULL;

-- AddForeignKey
ALTER TABLE "Task" ADD CONSTRAINT "Task_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
